"""add unique constraint to reviews booking

Revision ID: 560302e698fc
Revises: be7c2fa8fd93
Create Date: 2026-09-11 10:52:12.853884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560302e698fc'
down_revision: Union[str, Sequence[str], None] = 'be7c2fa8fd93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_booking_review', 'reviews', ['booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_booking_review', 'reviews', type_='unique')
    # ### end Alembic commands ###
