"""create financial transactions table

Revision ID: 73b0af8b079c
Revises: 1855a1a792a5
Create Date: 2026-09-11 12:29:40.405659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b0af8b079c'
down_revision: Union[str, Sequence[str], None] = '1855a1a792a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_transactions_id'), 'financial_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_reference_id'), 'financial_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_id'), 'financial_transactions', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_financial_transactions_type'), 'financial_transactions', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_transactions_type'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_reference_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_id'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    # ### end Alembic commands ###
