"""add location fields to businesses

Revision ID: 843024921912
Revises: dbcd0d7d23f9
Create Date: 2026-09-10 23:10:04.690691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843024921912'
down_revision: Union[str, Sequence[str], None] = 'dbcd0d7d23f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'businesses', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'businesses', 'provinces', ['province_id'], ['id'])
    op.drop_column('businesses', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'city_id')
    op.drop_column('businesses', 'province_id')
    # ### end Alembic commands ###
