"""create reward events table

Revision ID: 91f13f583b98
Revises: ce3773ff356e
Create Date: 2026-09-11 11:48:33.119748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f13f583b98'
down_revision: Union[str, Sequence[str], None] = 'ce3773ff356e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_events_booking_id'), 'reward_events', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reward_events_id'), 'reward_events', ['id'], unique=False)
    op.create_index(op.f('ix_reward_events_review_id'), 'reward_events', ['review_id'], unique=False)
    op.create_index(op.f('ix_reward_events_user_id'), 'reward_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_events_user_id'), table_name='reward_events')
    op.drop_index(op.f('ix_reward_events_review_id'), table_name='reward_events')
    op.drop_index(op.f('ix_reward_events_id'), table_name='reward_events')
    op.drop_index(op.f('ix_reward_events_booking_id'), table_name='reward_events')
    op.drop_table('reward_events')
    # ### end Alembic commands ###
