"""create review requests table

Revision ID: ce3773ff356e
Revises: 560302e698fc
Create Date: 2026-09-11 11:08:03.467049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3773ff356e'
down_revision: Union[str, Sequence[str], None] = '560302e698fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_requests_booking_id'), 'review_requests', ['booking_id'], unique=False)
    op.create_index(op.f('ix_review_requests_business_id'), 'review_requests', ['business_id'], unique=False)
    op.create_index(op.f('ix_review_requests_id'), 'review_requests', ['id'], unique=False)
    op.create_index(op.f('ix_review_requests_user_id'), 'review_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_requests_user_id'), table_name='review_requests')
    op.drop_index(op.f('ix_review_requests_id'), table_name='review_requests')
    op.drop_index(op.f('ix_review_requests_business_id'), table_name='review_requests')
    op.drop_index(op.f('ix_review_requests_booking_id'), table_name='review_requests')
    op.drop_table('review_requests')
    # ### end Alembic commands ###
