"""add location fields to users

Revision ID: dbcd0d7d23f9
Revises: a0dec67c4946
Create Date: 2026-09-10 22:49:03.970998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcd0d7d23f9'
down_revision: Union[str, Sequence[str], None] = 'a0dec67c4946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('province_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'])
    op.create_foreign_key(None, 'users', 'provinces', ['province_id'], ['id'])
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'city_id')
    op.drop_column('users', 'province_id')
    # ### end Alembic commands ###
